blog/urls.py
from django.urls import path, include
from . import views

#app_name = 'blog'

urlpatterns = [ # IP주소/blog/
    #path('', views.index),
    path('', views.PostList.as_view()),
    #path('<int:pk>/', views.single_post_page)
    path('<int:pk>/', views.PostDetail.as_view()),
    path('<int:pk>/new_comment/', views.new_comment),
    path('update_comment/<int:pk>/', views.CommentUpdate.as_view()),
    path('delete_comment/<int:pk>/', views.delete_comment),
    path('<int:pk1>/comment/<int:pk2>/new_commentofcomment/', views.new_commentofcomment),
    path('update_coc/<int:pk>/',views.CommentOfCommentUpdate.as_view()),
    path('delete_coc/<int:pk>/',views.delete_coc),
    path('category/<str:slug>/', views.category_page),
    path('tag/<str:slug>/', views.tag_page),
    path('create_post/', views.PostCreate.as_view()),
    path('update_post/<int:pk>/', views.PostUpdate.as_view()),
    path('delete_post/<int:pk>/', views.delete_post),
    path('search/<str:q>/', views.PostSearch.as_view()),
#    path('test/', include('rest_framework.urls', namespace='rest_framework_category')),
]

myDjango/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from rest_framework import routers
from blog import views

router = routers.DefaultRouter()
router.register(r'tests', views.postViewSet)

urlpatterns = [ # IP주소
    path('admin/', admin.site.urls),        # IP주소/admin
    path('blog/', include('blog.urls')),    # IP주소/blog
    path('markdownx/', include('markdownx.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('single_pages.urls')),  # IP주소
    path('drf/', include(router.urls))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from markdownx.models import MarkdownxField
from markdownx.utils import markdown
import os

# Create your models here.

class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/blog/tag/{self.slug}/'

class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/blog/category/{self.slug}/'

    class Meta:
        verbose_name_plural = 'Categories'

class Post(models.Model):
    title = models.CharField(max_length=30)
    hook_text = models.CharField(max_length=100, blank=True)
    content = MarkdownxField() # models.TextField()

    head_image = models.ImageField(upload_to='blog/images/%Y/%m/%d/', blank=True)
    file_upload = models.FileField(upload_to='blog/files/%Y/%m/%d/', blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)

    tags = models.ManyToManyField(Tag, blank=True)

    def __str__(self):
        return f'[{self.pk}]{self.title}  :: {self.author} :  {self.created_at}'

    def get_absolute_url(self):
        return f'/blog/{self.pk}/'

    def get_content_markdown(self):
        return markdown(self.content)

    def get_file_name(self):
        return os.path.basename(self.file_upload.name)

    def get_file_ext(self):
        return self.get_file_name().split('.')[-1] # .으로 분리 후 마지막

    def get_avatar_url(self):
        if self.author.socialaccount_set.exists():
            return self.author.socialaccount_set.first().get_avatar_url()
        else:
            return 'https://dummyimage.com/50x50/ced4da/6c757d.jpg'

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.author}::{self.content}'

    def get_absolute_url(self):
        return f'{self.post.get_absolute_url()}#comment-{self.pk}'

    def get_avatar_url(self):
        if self.author.socialaccount_set.exists():
            return self.author.socialaccount_set.first().get_avatar_url()
        elif self.author.is_superuser or self.author.is_staff:
            img = "/static/blog/images/staff_profile.png"
            return img
        else:
            return f'https://doitdjango.com/avatar/id/1398/071b01be365056e8/svg/{self.author.email}'

class CommentOfComment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    parent_Comment = models.ForeignKey(Comment, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.author} : {self.content}'

    def get_absolute_url(self):
        return f'{self.parent_Comment.get_absolute_url()}'

blog/forms.py
from .models import Comment, CommentOfComment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

class CommentOfCommentForm(forms.ModelForm):
    class Meta:
        model = CommentOfComment
        fields=('content',)

blog/views.py
from django.shortcuts import render, redirect
from .models import Post, Category, Tag, Comment, CommentOfComment
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.utils.text import slugify
from .forms import CommentForm, CommentOfCommentForm
from django.shortcuts import get_object_or_404
from django.db.models import Q
from rest_framework import viewsets
from .serializers import postSerializer


class postViewSet(viewsets.ModelViewSet) :
    queryset = Post.objects.all()
    serializer_class = postSerializer


# Create your views here.
class PostList(ListView):
    model = Post
    ordering = '-pk'
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostList, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count
        return context
    # 템플릿은 모델명_list.html
    # 매개변수는 모델명_list

class PostDetail(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count
        context['comment_form'] = CommentForm
        context['commentofComment_form'] = CommentOfCommentForm
        return context
    # 템플릿은 모델명_detail.html
    # 매개변수는 모델명

def delete_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.user.is_authenticated and request.user == post.author:
        post.delete()
        return redirect('/blog/')
    else:
        return PermissionDenied

class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'hook_text', 'content', 'head_image', 'file_upload', 'category'] # , 'tags'

    template_name = 'blog/post_update_form.html'

    def form_valid(self, form):
        response = super(PostUpdate,self).form_valid(form)
        self.object.tags.clear()
        tags_str = self.request.POST.get('tags_str')
        if tags_str:
            tags_str = tags_str.strip()
            tags_str = tags_str.replace(',', ';')
            tags_list = tags_str.split(';')
            for t in tags_list:
                t = t.strip()
                tag, is_tag_created = Tag.objects.get_or_create(name=t)
                if is_tag_created:
                    tag.slug = slugify(t, allow_unicode=True)
                    tag.save()
                self.object.tags.add(tag)
        return response

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(PostUpdate,self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

    def get_context_data(self, **kwargs):
        context = super(PostUpdate, self).get_context_data()
        if self.object.tags.exists():
            tags_str_list = list()
            for t in self.object.tags.all():
                tags_str_list.append(t.name)
            context['tags_str_default'] = ';'.join(tags_str_list)
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count
        return context

class PostCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Post
    fields = ['title', 'hook_text', 'content', 'head_image', 'file_upload', 'category'] # , 'tags'

    # 템플릿은 모델명_form.html

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated and (current_user.is_superuser or current_user.is_staff):
            form.instance.author = current_user
            response = super(PostCreate, self).form_valid(form)
            tags_str = self.request.POST.get('tags_str')
            if tags_str:
                tags_str = tags_str.strip()
                tags_str = tags_str.replace(',',';')
                tags_list = tags_str.split(';')
                for t in tags_list:
                    t = t.strip()
                    tag, is_tag_created = Tag.objects.get_or_create(name=t)
                    if is_tag_created:
                        tag.slug = slugify(t, allow_unicode=True)
                        tag.save()
                    self.object.tags.add(tag)
            return response
        else:
            return redirect('/blog/')

    def get_context_data(self, **kwargs):
        context = super(PostCreate, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count
        return context

class PostSearch(PostList): # ListView 상속, post_list 데이터, post_list 템플릿
    paginate_by = None

    def get_queryset(self):
        q = self.kwargs['q']
        post_list = Post.objects.filter(
            Q(title__contains=q) | Q(tags__name__contains=q)
        ).distinct()
        return post_list

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostSearch, self).get_context_data()
        q = self.kwargs['q']
        context['search_info'] = f'Search: {q} ({self.get_queryset().count()})'
        return context

def category_page(request, slug):
    if slug == 'no_category' :
        category = '미분류'
        post_list = Post.objects.filter(category=None)
    else :
        category = Category.objects.get(slug=slug)
        post_list = Post.objects.filter(category=category)

    return render(request, 'blog/post_list.html', {
        'category' : category,
        'post_list' : post_list,
        'categories' : Category.objects.all(),
        'no_category_post_count' : Post.objects.filter(category=None).count
    })

def tag_page(request, slug):
    tag = Tag.objects.get(slug=slug)
    post_list = tag.post_set.all()

    return render(request, 'blog/post_list.html', {
        'tag' : tag,
        'post_list' : post_list,
        'categories': Category.objects.all(),
        'no_category_post_count': Post.objects.filter(category=None).count
    })

def new_comment(request, pk):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=pk)
        if request.method == 'POST':
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.post = post
                comment.author = request.user
                comment.save()
                return redirect(comment.get_absolute_url())
        else : # GET
            return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied

def delete_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post = comment.post
    if request.user.is_authenticated and request.user == comment.author:
        comment.delete()
        return redirect(post.get_absolute_url())
    else:
        PermissionDenied

class CommentUpdate(LoginRequiredMixin, UpdateView):
    model = Comment
    form_class = CommentForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(CommentUpdate,self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

def new_commentofcomment(request,pk1,pk2):
    if request.user.is_authenticated:
        post = get_object_or_404(Post,pk=pk1)
        parent = get_object_or_404(Comment, pk=pk2)
        #포스트 모델에서 pk=pk인거 가지고 오기
        if request.method == 'POST':
            commentOfComment_form = CommentOfCommentForm(request.POST)
            if commentOfComment_form.is_valid():
                comment = commentOfComment_form.save(commit=False)
                comment.parent_Comment = parent
                comment.author = request.user
                comment.save()
                return redirect(post.get_absolute_url())
        else: #GET으로 온 경우
            return redirect(parent.get_absolute_url())
    else:
        raise PermissionDenied

def delete_coc(request,pk):
    coc = get_object_or_404(CommentOfComment, pk=pk)
    parent = coc.parent_Comment.post

    if request.user.is_authenticated and request.user == coc.author:
        coc.delete()
        return redirect(parent.get_absolute_url())
    else:
        PermissionDenied

class CommentOfCommentUpdate(LoginRequiredMixin,UpdateView):
    model = CommentOfComment
    form_class = CommentOfCommentForm

    # CreateView,UpdateView 이던지,,, form을 사용하면, 템플릿이 model명_forms로 자동을 만들어짐.
    # 템플릿 모델명_forms : comment_form

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(CommentOfCommentUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

#def index(request):
#    posts = Post.objects.all().order_by('-pk')
#    return render(request, 'blog/index.html', {'posts':posts})

#def single_post_page(request, pk):
#    post = Post.objects.get(pk=pk)
#    return render(request, 'blog/single_post_page.html', {'post':post})

blog/templates/blog/CommentOfComment_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
   대댓글 수정
{% endblock %}

{% block main_area %}

    <h1>Edit Comment of Comment</h1>
    <hr>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {{ form | crispy }}

        <br>
        <button type="submit" class="btn btn-secondary float-right">완료</button>
    </form>
    <br><br>
{% endblock %}

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block head_title %}Blog{% endblock %}</title>
  <link href="{% static 'blog/bootstrap/bootstrap.min.css' %}" rel="stylesheet" type="text/css" media="screen">
  <script src="https://kit.fontawesome.com/54c8fd0744.js" crossorigin="anonymous"></script>
</head>
<body>
  {% include 'blog/navbar.html' %}

  <div class="container">
    <div class="row">
      <div class="col-md-8 col-lg-9" id="main-area">
        {% block main_area %}
        {% endblock %}
      </div>

      <div class="col-md-4 col-lg-3">
        {% include 'blog/sidebar.html' %}
      </div>
    </div>
  </div>

  {% include 'blog/footer.html' %}

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog/comment_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
    Edit Comment - Blog
{% endblock %}

{% block main_area %}
    <h1>Edit Comment</h1>
    <hr/>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {{form|crispy}}

        <br/>
        <button type="submit" class="btn btn-primary float-right">Submit</button>
    </form>
    {{ form.media }}
 {% endblock %}

blog/templates/blog/footer.html
  <!-- Footer-->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; InternetProgramming 2022</p>
    </div>
  </footer>

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Blog</title>
</head>
<body>
    <h1>Blog</h1>

    {% for p in posts %}
        <hr/>
        <h2><a href="{{p.get_absolute_url}}">{{p.title}}</a></h2>
        <h4>{{p.created_at}}</h4>
        <p>{{p.content}}</p>
    {% endfor %}
</body>
</html>

blog/templates/blog/navbar.html
{% load socialaccount %}
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand" href="/">InternetProgramming</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/blog/">Blog</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/about_me/">About Me</a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
           <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {% if user.socialaccount_set.all.0.get_avatar_url %}
              <img class="rounded-circle mr-3" src="{{user.socialaccount_set.all.0.get_avatar_url}}" alt="" width="25px" />
              {% elif user.is_superuser or user.is_staff %}
                <img class="rounded-circle mr-1" src="{% static 'blog/images/staff_profile.png' %}" width="25px">
              {% else %}
              <img class="rounded-circle mr-3" src="https://doitdjango.com/avatar/id/1398/071b01be365056e8/svg/{{user.email}}" alt="" width="25px" />
              <!-- https://dummyimage.com/50x50/ced4da/6c757d.jpg -->
              {% endif %}
              {{user.username}}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="/accounts/logout/">LogOut</a>
            </div>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="#" data-toggle="modal" data-target="#loginModal">LogIn</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  <!-- Modal -->
  <div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel"><i class="fa-solid fa-right-to-bracket"></i>Log In</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="row">
            <div class="col-6">
              <a role="button" type="button" class="btn btn-outline-dark btn-block btn-sm"
                href="{% provider_login_url 'google' %}">
                <i class="fa-brands fa-google"></i> LogIn with Google
              </a>
              <a role="button" class="btn btn-outline-dark btn-block btn-sm" href="/accounts/login/">
                <i class="fa-regular fa-envelope"></i> LogIn with Email
              </a>
            </div>
            <div class="col-6">
              <a role="button" class="btn btn-outline-dark btn-block btn-sm" href="/accounts/signup/">
                <i class="fa-regular fa-envelope"></i> SignUp with Email
              </a>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>

blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
    Create Post - Blog
{% endblock %}

{% block main_area %}
    <h1>Create New Post</h1>
    <hr/>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {{form | crispy}}
        <div id="div_id_tags_str">
            <label for="id_tags">Tags:</label>
            <input type="text" id="id_tags" name="tags_str" class="textinput textInput form-control">
        </div>
        <br/>
        <button type="submit" class="btn btn-primary float-right">Submit</button>
    </form>
    {{ form.media }}
 {% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block main_area %}
    {% if user.is_authenticated %}
        {% if user.is_superuser or user.is_staff %}
            <a class="btn btn-info btn-sm float-right" href="/blog/create_post/" role="button">
                <i class="fas fa-pen"> New Post</i>
            </a>
        {% endif %}
    {% endif %}
        <h1>Blog
          {% if search_info %}
             <span class="badge badge-secondary">{{search_info}}</span>
          {% endif %}
          {% if category %}
            <span class="badge badge-secondary">{{category}}</span>
          {% endif %}
          {% if tag %}
            <i class="fas fa-tags"></i><span class="badge badge-secondary">{{tag}} ({{tag.post_set.count}})</span>
          {% endif %}
        </h1>
        <!-- Featured blog post-->
        {% if post_list.exists %}
        {% for p in post_list %}
        <div class="card mb-4" id="post-{{p.pk}}">
          {% if p.head_image %}
          <img class="card-img-top" src="{{p.head_image.url}}" alt="{{p}}의 head_image" />
          {% else %}
          <img class="card-img-top" src="https://picsum.photos/seed/{{p.pk}}/800/200" alt="random image" />
          {% endif %}
          <div class="card-body">
            {% if p.category %}
            <span class="badge badge-secondary float-right"><a href="{{p.category.get_absolute_url}}">{{p.category}}</a></span>
            {% else %}
            <span class="badge badge-secondary float-right"><a href="/blog/category/no_category/">미분류</a></span>
            {% endif %}
            <h2 class="card-title">{{p.title | upper}}</h2>
            {% if p.hook_text %}
            <h5 class="card-muted">{{p.hook_text}}</h5>
            {% endif %}
            <p class="card-text">{{p.get_content_markdown | truncatewords_html:10 | safe}}</p>
            {% if p.tags.exists %}
              <i class="fas fa-tags"></i>
              {% for tag in p.tags.iterator %}
                <span class="badge badge-pill badge-light"><a href="{{tag.get_absolute_url}}">{{tag}}</a></span>
              {% endfor %}
              <br><br>
            {% endif %}
            <a class="btn btn-primary" href="{{p.get_absolute_url}}">Read more →</a>
          </div>
          <div class="card-footer">
            <div class="small text-muted">{{p.created_at | date:"Y-m-d h:m:s"}}</div>
            <a href="#">{{p.author | upper}}</a>
          </div>
        </div>
        {% endfor %}
        {% else %}
        <h5>아직 게시물이 없습니다.</h5>
        {% endif %}

        {% if is_paginated %}
        <!-- Pagination-->
        <nav aria-label="Pagination">
          <hr class="my-0" />
          <ul class="pagination justify-content-center my-4">
              {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}" tabindex="-1" aria-disabled="true">Newer</a></li>
              {% else %}
                <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1" aria-disabled="true">Newer</a></li>
              {% endif %}
              {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}" tabindex="-1" aria-disabled="true">Older</a></li>
              {% else %}
                <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1" aria-disabled="true">Older</a></li>
              {% endif %}
          </ul>
        </nav>
        {% endif %}
{% endblock %}

blog/templates/blog/post_update_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
    Update Post - Blog
{% endblock %}

{% block main_area %}
    <h1>Update Post</h1>
    <hr/>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {{form|crispy}}
        <div id="div_id_tags_str">
            <label for="id_tags">Tags:</label>
            <input type="text" id="id_tags" name="tags_str" value="{{tags_str_default}}" class="textinput textInput form-control">
        </div>
        <br/>
        <button type="submit" class="btn btn-primary float-right">Submit</button>
    </form>
    {{ form.media }}
 {% endblock %}

blog/templates/blog/sidebar.html
        <!-- Search widget-->
        <div class="card mb-4">
          <div class="card-header">Search</div>
          <div class="card-body">
            <div class="input-group">
              <input id="search-input" class="form-control" type="text" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" />
              <button class="btn btn-primary" id="button-search" type="button" onclick="searchPost()">Go!</button>
            </div>
          </div>
        </div>
        <script>
            function searchPost(){
                let searchValue = document.getElementById('search-input').value.trim();
                if(searchValue.length > 1){
                    location.href = "/blog/search/"+searchValue+"/";
                }
                else{
                    alert('검색어('+searchValue+')가 너무 짧습니다.');
                }
            };
            document.getElementById('search-input').addEventListener('keyup', function(event){
                    if(event.key === 'Enter'){
                        searchPost();
                    }
                });
        </script>
        <!-- Categories widget-->
        <div class="card mb-4" id="category_card">
          <div class="card-header">Categories</div>
          <div class="card-body">
            <div class="row">

                <ul>
                  {% for c in categories %}
                    <li><a href="{{c.get_absolute_url}}">{{c}} ({{c.post_set.count}})</a></li>
                  {% endfor %}
                    <li><a href="/blog/category/no_category/">미분류 ({{no_category_post_count}})</a></li>
                </ul>

            </div>
          </div>
        </div>

blog/templates/blog/single_post_page.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>{{post.title}} - Blog</title>
</head>
<body>
    <nav>
        <a href="/blog/">Blog</a>
    </nav>
    <h1>{{post.title}}</h1>
    <h4>{{post.created_at}}</h4>
    <p>{{post.content}}</p>
    <hr/>
    <h3>여기에 댓글이 오겠죠?</h3>
</body>
</html>